version: 2

sources:
  - name: raw
    database: dbt-gcp-8abd
    schema: dbt_velib
    freshness:
      warn_after:
        count: 1
        period: week
      error_after:
        count: 2
        period: week
    loaded_at_field: extracted_at
    tables:
      - name: raw_velib_stations